INSERT INTO APP.CUSTOMER(CUSTOMERID, ADDR1, ADDR2, ADDRCITY, ADDRSTATE, ADDRZIP, FIRSTNAME, LASTNAME, PASSWORD, PHONE) VALUES ('plants@plantsbywebsphere.ibm.com', '123 Main Street', 'Apt. C', 'Raleigh', 'NC', '27604', 'David', 'Grover', 'plants', '919-555-1234')
GO
INSERT INTO APP.CUSTOMER(CUSTOMERID, ADDR1, ADDR2, ADDRCITY, ADDRSTATE, ADDRZIP, FIRSTNAME, LASTNAME, PASSWORD, PHONE) VALUES ('test@test.com', 'Test', 'Test', 'Tes', 'TX', '11111', 'Test', 'Test', 'test', '1111111111')
GO
INSERT INTO APP.CUSTOMER(CUSTOMERID, ADDR1, ADDR2, ADDRCITY, ADDRSTATE, ADDRZIP, FIRSTNAME, LASTNAME, PASSWORD, PHONE) VALUES ('demo@ibm.com', 'IBM Lab', '', 'Somewhere', 'NC', '12345', 'Demo', 'User', 'password', '111-111-1111')
GO
